init:
    - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '7'

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install
    - ls node_modules/
    - ls node_modules/.bin/

version: '{build}'

test_script:
    - npm --version
    - node --version
    - npm test
