'use strict';

let VSLOperatorType = Object.freeze({
    None: 0,
    Range: 1,
    Assign: 2,
    StrictAssign: 3,
    LeftShiftEquals: 4,
    RightShiftEquals: 5,
    PlusEquals: 6,
    MinusEquals: 7,
    DivideEquals: 8,
    TimesEquals: 9,
    ModuloEquals: 10,
    PowerEquals: 11,
    BitwiseAndEquals: 12,
    BitwiseOrEquals: 13,
    BitwiseXorEquals: 14,
    Is: 15,
    IsSubclass: 16,
    Equal: 17,
    NotEqual: 18,
    Spaceship: 19,
    LessThanOrEqual: 20,
    GreaterThanOrEqual: 21,
    LessThan: 22,
    GreaterThan: 23,
    LogicalAnd: 24,
    LogicalOr: 25,
    LogicalXor: 26,
    LogicalNot: 27,
    LeftShift: 28,
    RightShift: 29,
    Plus: 30,
    Minus: 31,
    Divide: 32,
    Times: 33,
    Modulo: 34,
    Power: 35,
    BitwiseAnd: 36,
    BitwiseOr: 37,
    BitwiseXor: 38,
    BitwiseNot: 39,
    Cast: 40,
    Map: 41,
    Chain: 42,
    Negate: 43,
    Positive: 44,
    LENGTH: 45
});

export default VSLOperatorType;